// Functions that handle the PPM or PGM image
// By reading pixels from the inputted file and loading them into memory

#include "image.h"

static void load_ascii_image_from_disk(image_t *image, const char *filename);
static void load_binary_image_from_disk(image_t *image, const char *filename);

/**
 * Load function which handles both ascii and binary, greyscale or color
 * By calling the necessary functions.
 * It also allocates memory for the images by calling the alloc functions
 */
void load_image_from_disk(image_t *image, selection_t *select, const char *filename)
{
	// OPEN FILE
	FILE *in = fopen(filename, "rt");
	if (!in) {
		printf("Could not load %s\n", filename);
		// CLEAR CURRENT IMAGE
		if (image_is_greyscale(image)) {
			free_greyscale(image);
		}
		if (image_is_color(image)) {
			free_color(image);
		}
		select->all = false;
		select->x_start = 0;
		select->y_start = 0;
		select->x_end = 0;
		select->y_end = 0;
		return;
	}

	// READ THE FORMAT
	if (fscanf(in, "%s", image->format) != 1) {
		fclose(in);
		printf("Failed to load %s\n", filename);
		// CLEAR THE CURRENT IMAGE
		if (image_is_greyscale(image)) {
			free_greyscale(image);
		}
		if (image_is_color(image)) {
			free_color(image);
		}
		return;
	}
	// CLOSE THE FILE
	fclose(in);

	// FREE IF ALREADY ALLOCATED
	if (image_is_greyscale(image)) {
		free_greyscale(image);
	}
	if (image_is_color(image)) {
		free_color(image);
	}

	// FORMATS
	if (strcmp(image->format, "P1") == 0 ||
		strcmp(image->format, "P2") == 0 ||
		strcmp(image->format, "P3") == 0) {
		load_ascii_image_from_disk(image, filename);
	}
	if (strcmp(image->format, "P4") == 0 ||
		strcmp(image->format, "P5") == 0 ||
		strcmp(image->format, "P6") == 0) {
		load_binary_image_from_disk(image, filename);
	}
	// UPDATE SELECTION IF LOAD SUCCESSFULL
	if (image->greyscale_matrix || image->color_matrix) {
		select->all = true;
		select->x_start = 0;
		select->y_start = 0;
		select->x_end = image->cols;
		select->y_end = image->rows;
		printf("Loaded %s\n", filename);
	}

}

/**
 * Builds an image_t object from a buffer.
 * The buffer is generated by libcurl, it contains the http response,
 * which is the downloaded file in a PPM format.
 */
bool load_binary_image_from_buffer(image_t *image, selection_t *select, const char* buffer)
{
	if (!buffer) {
		fprintf(stderr, "Buffer is empty!\n");
		return false;
	}
	
	unsigned int offset = 0;
	int bytes_read = 0;

	// READ FIRST LINE (format)
	sscanf(buffer, "%s %n", image->format, &bytes_read);
	if (strcmp(image->format, "P6") != 0) {
		fprintf(stderr, "Could not read format or format is not P6.\n");
		return false;
	}
	offset += bytes_read;
	bytes_read = 0;

	int temp_cols = -1;
	int temp_rows = -1;
	sscanf(buffer + offset, "%d %d %n", &temp_cols, &temp_rows, &bytes_read);

	if (temp_cols <= 0 || temp_rows <= 0) {
		fprintf(stderr, "Could not read image size\n");
		return false;
	}
	offset += bytes_read;
	bytes_read = 0;

	int maxval = -1;
	sscanf(buffer + offset, "%d%n", &maxval, &bytes_read);
	if (maxval == -1) {
		fprintf(stderr, "Could not read maxval\n");
		return false;
	}
	offset += bytes_read + 1;	// +1 for newline
	bytes_read = 0;

	if (image_is_color(image)) {
		free_color(image);
	}
	image->cols = temp_cols;
	image->rows = temp_rows;
	alloc_color(image);

	for (int i = 0; i < image->rows; i++) {
		for (int j = 0; j < image->cols; j++) {
			memcpy(&image->color_matrix[i][j].r, buffer + offset, sizeof(unsigned char));
			offset += sizeof(unsigned char);
			memcpy(&image->color_matrix[i][j].g, buffer + offset, sizeof(unsigned char));
			offset += sizeof(unsigned char);
			memcpy(&image->color_matrix[i][j].b, buffer + offset, sizeof(unsigned char));
			offset += sizeof(unsigned char);
		}
	}
	
	if (image_is_color(image)) {
		select->all = true;
		select->x_start = 0;
		select->y_start = 0;
		select->x_end = image->cols;
		select->y_end = image->rows;
	}

	return true;
}

static void load_ascii_image_from_disk(image_t *image, const char *filename)
{
	// OPEN FILE
	FILE *in = fopen(filename, "rt");
	if (!in) {
		printf("Failed to load the text file  %s\n", filename);
		return;
	}

	// READ FIRST LINE AGAIN
	char ignore[1024];
	fscanf(in, "%s", ignore);

	// P2 GREYSCALE FORMAT
	if (strcmp(image->format, "P2") == 0) {
		// READ COLLS AND ROWS
		fscanf(in, "%d %d", &image->cols, &image->rows);

		// READ MAXVAL 255
		fscanf(in, "%d", &image->maxval);

		alloc_greyscale(image);

		// ASSIGN VALUES
		for (int i = 0 ; i < image->rows; i++) {
			for (int j = 0; j < image->cols; j++) {
				int value;
				fscanf(in, "%d", &value);
				// READ INT AND CAST TO UNSIGNED CHAR AFTERWARDS
				image->greyscale_matrix[i][j] = (unsigned char)value;
			}
		}

	}
	// P3 RGB FORMAT
	if (strcmp(image->format, "P3") == 0) {
		// READ COLLS AND ROWS
		fscanf(in, "%d %d", &image->cols, &image->rows);
		// READ MAXVAL 255
		fscanf(in, "%d", &image->maxval);

		alloc_color(image);

		//ASSIGN VALUES
		for (int i = 0; i < image->rows; i++) {
			for (int j = 0; j < image->cols; j++) {
				int r, g, b;
				fscanf(in, "%d %d %d", &r, &g, &b);
				// READ INT AND CAST TO UNSIGNED CHAR AFTERWARDS
				image->color_matrix[i][j].r = (unsigned char)r;
				image->color_matrix[i][j].g = (unsigned char)g;
				image->color_matrix[i][j].b = (unsigned char)b;
			}
		}
	}
	// CLOSE THE FILE
	fclose(in);
}

static void load_binary_image_from_disk(image_t *image, const char *filename)
{
	// OPEN FILE
	FILE *in = fopen(filename, "rb");
	if (!in) {
		printf("Failed to load the binary file %s\n", filename);
		return;
	}

	// READ FIRST LINE AGAIN
	char ignore[1024];
	fscanf(in, "%s", ignore);

	// P5 GREYSCALE FORMAT
	if (strcmp(image->format, "P5") == 0) {
		fscanf(in, "%d %d", &image->cols, &image->rows);
		// READ MAXVAL 255
		fscanf(in, "%d\n", &image->maxval);

		alloc_greyscale(image);

		// ASSIGN VALUES BY READING ONE ROW AT A TIME
		for (int i = 0 ; i < image->rows; i++) {
			fread(image->greyscale_matrix[i], sizeof(unsigned char), image->cols, in);
		}
	}
	// P6 RGB FORMAT
	if (strcmp(image->format, "P6") == 0) {
		fscanf(in, "%d %d", &image->cols, &image->rows);
		// READ MAXVAL 255
		fscanf(in, "%d\n", &image->maxval);

		alloc_color(image);

		// ASSIGN VALUES BY READING ONE ROW AT A TIME
		for (int i = 0; i < image->rows; i++) {
			fread(image->color_matrix[i], sizeof(pixel_t), image->cols, in);
		}
	}
	// CLOSE THE FILE
	fclose(in);
}
